name: Mindful fotograferen
favicon: null
layout_spectrum: 0.5985886508133262
typography_spectrum: 0.764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.052158448146656156
  lightness: 0.02715135714970529
  saturation: 0.042185560101643205
  rhythmicContrast: 0.6767034037038684
purpose: []
